name: ks-xmonad
version: 0.0.0
synopsis: my xmonad configuration

executables:
  xmonad:
    main: xmonad.hs
    source-dirs: [".", "lib"]
    dependencies:
      - "base"
      - "containers"
      - "xmonad"
      - "xmonad-contrib"
